// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraryManagementSystem.Models
{
    public partial class Book
    {
        public Book()
        {
            Copies = new HashSet<Copy>();
            Publications = new HashSet<Publication>();
        }

        [Key]
        [Column("ISBN")]
        [StringLength(50)]
        public string Isbn { get; set; }
        [Required]
        [StringLength(50)]
        public string Title { get; set; }
        [Required]
        [StringLength(100)]
        public string Description { get; set; }
        [StringLength(50)]
        public string Genre { get; set; }
        public int? Year { get; set; }
        public bool IsAvailable { get; set; }
        public int NumberOfCopies { get; set; }

        [InverseProperty(nameof(Copy.IsbnNavigation))]
        public virtual ICollection<Copy> Copies { get; set; }
        [InverseProperty(nameof(Publication.IsbnNavigation))]
        public virtual ICollection<Publication> Publications { get; set; }
    }
}