// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraryManagementSystem.Models
{
    public partial class Copy
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int CopyId { get; set; }
        public bool IsReturned { get; set; }
        public int? LoanId { get; set; }
        [Required]
        [Column("ISBN")]
        [StringLength(50)]
        public string Isbn { get; set; }

        [ForeignKey(nameof(Isbn))]
        [InverseProperty(nameof(Book.Copies))]
        public virtual Book IsbnNavigation { get; set; }
        [ForeignKey(nameof(LoanId))]
        [InverseProperty("Copies")]
        public virtual Loan Loan { get; set; }
    }
}