// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LibraryManagementSystem.Models
{
    public partial class User
    {
        public User()
        {
            Loans = new HashSet<Loan>();
            Messages = new HashSet<Message>();
        }

        [Key]
        public int UserId { get; set; }
        [Required]
        [StringLength(50)]
        public string Name { get; set; }
        [Required]
        [StringLength(50)]
        public string Email { get; set; }
        [Required]
        [StringLength(50)]
        public string Password { get; set; }
        public bool IsAdmin { get; set; }

        [InverseProperty(nameof(Loan.User))]
        public virtual ICollection<Loan> Loans { get; set; }
        [InverseProperty(nameof(Message.User))]
        public virtual ICollection<Message> Messages { get; set; }
    }
}